"""New field datetime

Revision ID: a6baeb137bf5
Revises: 81ac8c81e086
Create Date: 2025-06-30 14:07:03.610814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6baeb137bf5'
down_revision: Union[str, Sequence[str], None] = '81ac8c81e086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature', 'date_time')
    # ### end Alembic commands ###
